### PR TITLE
Add possibility to apply gradient color to border

### PR DESCRIPTION
**Pull request by nshaposhnik**
In order to select colors to be used for gradient, you need to pass string in xml like range:border_gradient_colors="#f05151;#4a90e2;#4a90e2" , with ';' separators. Haven't found better solution, feel free to suggest of course.

### CODE REVIEW

**Comment by milosmns** [comment]
I'll try to merge it over the weekend. Thanks for participating in the project 👍

**Comment by milosmns** [comment]
I'll try to publish today or tomorrow

**Comment by milosmns** [comment]
Published v1.4.1 @ https://bintray.com/milosmns/maven/slider/1.4.1
Docs updated as well, README now points to the latest version

**Comment by nshaposhnik** [comment]
Ok, thank you

**Pull request merged**
